// ============================================================
// CATALOGO DE PRODUTOS
// Para adicionar/editar produtos, modifique este arquivo.
// Para adicionar fotos: coloque na pasta /images/ e atualize
// o array "images" de cada produto.
// ============================================================

const WHATSAPP_NUMBER = "5516996385030";

const products = [
    {
        id: 1,
        title: "3 Cadeiras Altas de Balcao (Madeira)",
        category: "moveis",
        price: 1100,
        originalPrice: 2700,
        description: "Madeira natural com assento estofado bege/creme (couro sintetico). Altura ~1,1m, profundidade 40cm. Conjunto com 3 unidades.",
        condition: "good",
        conditionText: "Bom estado - 4 anos de uso",
        images: ["images/IMG_3893.jpg", "images/IMG_3894.jpg", "images/IMG_3895.jpg"],
        placeholder: "🪑",
        available: null,
        sold: false
    },
    {
        id: 2,
        title: "2 Espreguicadeiras Aluminio + Textilene",
        category: "moveis",
        price: 750,
        originalPrice: 2360,
        description: "Aluminio preto com textilene bege. 5 posicoes reclinaveis. Conjunto com 2 unidades. Obs: uma com parafuso levemente solto no encosto.",
        condition: "fair",
        conditionText: "Bom estado - 5 anos, area externa",
        images: ["images/espreguicadeira_1.jpg", "images/espreguicadeira_2.jpg"],
        placeholder: "🏖️",
        available: null,
        sold: false
    },
    {
        id: 3,
        title: "Kit Aparador + 4 Cadeiras (Varanda)",
        category: "moveis",
        price: 1400,
        originalPrice: 2000,
        description: "Metal preto + rattan com tampo branco. Largura ~1,95m. Ideal para varanda ou area gourmet.",
        condition: "good",
        conditionText: "Bom estado - 4 anos, uso interno",
        images: ["images/IMG_4059.jpg", "images/IMG_4060.jpg"],
        placeholder: "🍽️",
        available: null,
        sold: false
    },
    {
        id: 4,
        title: "Cama Infantil Montessori MDF + Colchao",
        category: "camas",
        price: 350,
        originalPrice: 950,
        description: "100% MDF formato casinha. Medidas: 1,42m x 69cm x 1,61m. Obs: leve defeito no encaixe, pontinha quebrada. Acompanha colchao.",
        condition: "fair",
        conditionText: "Estado regular - 4 anos de uso",
        images: ["images/IMG_4095.jpg", "images/IMG_4096.jpg", "images/IMG_4098.jpg"],
        placeholder: "🏠",
        available: "09/04",
        sold: false
    },
    {
        id: 5,
        title: "Cama Montessori Madeira Macica + Colchao",
        category: "camas",
        price: 800,
        originalPrice: 1500,
        description: "Madeira macica feita por marceneiro, excelente qualidade. Medidas: 1,91m x 91cm x 1,3m. SEM DEFEITOS. Acompanha colchao.",
        condition: "excellent",
        conditionText: "Excelente estado - 8 anos, sem defeitos",
        images: ["images/IMG_4101.jpg", "images/IMG_4102.jpg", "images/IMG_4103.jpg"],
        placeholder: "🛏️",
        available: "09/04",
        sold: false
    },
    {
        id: 6,
        title: "Tapete Grande 2,5m x 3m - Jacquard",
        category: "decoracao",
        price: 500,
        originalPrice: 1700,
        description: "Jacquard cinza/bege, marca Havan. Limpo e higienizado. Dimensoes: 2,5m x 3m.",
        condition: "good",
        conditionText: "Bom estado - 4 anos, limpo",
        images: ["images/IMG_4105.jpg", "images/IMG_4104.jpg"],
        placeholder: "🟫",
        available: null,
        sold: false
    },
    {
        id: 7,
        title: "Capacete Specialized S-Works Prevail II Vent",
        category: "esporte",
        price: 1500,
        originalPrice: 3020,
        description: "Aramida + Carbon Fiber (AirCage). MUITO LEVE: apenas 240g. Tamanho M (55-59cm). Seminovo, sem viseira. Top de linha da Specialized!",
        condition: "excellent",
        conditionText: "Seminovo - excelente estado",
        images: ["images/IMG_4111.jpg", "images/IMG_4112.jpg", "images/IMG_4113.jpg", "images/IMG_4114.jpg"],
        placeholder: "⛑️",
        available: null,
        sold: false
    },
    {
        id: 8,
        title: "Capacete Specialized Align",
        category: "esporte",
        price: 180,
        originalPrice: 349,
        description: "Tamanho ajustavel 54-62cm. Bom estado geral.",
        condition: "good",
        conditionText: "Bom estado",
        images: ["images/IMG_4108.jpg", "images/IMG_4109.jpg", "images/IMG_4110.jpg"],
        placeholder: "⛑️",
        available: null,
        sold: false
    },
    {
        id: 9,
        title: "Bicicleta Rava Storm Limited Aro 29\"",
        category: "esporte",
        price: 3000,
        originalPrice: 4499,
        description: "Aro 29\", amarelo neon + preto. Todas pecas Shimano (qualidade premium). Recem revisada.",
        condition: "excellent",
        conditionText: "Excelente - recem revisada",
        images: ["images/IMG_4116.jpg", "images/IMG_4117.jpg", "images/IMG_4118.jpg", "images/IMG_4119.jpg", "images/IMG_4120.jpg"],
        placeholder: "🚴",
        available: "09/04",
        sold: false
    },
    {
        id: 10,
        title: "Lava-louca Electrolux 10 Servicos",
        category: "eletro",
        price: 1400,
        originalPrice: 2500,
        description: "Meia cuba, preto/inox, painel touch digital. Medidas: 44cm x 85cm. Programas: Inteligente, Normal/Eco, Panelas, Delicado, Express 30', Acquajet, Higienizar 70°C.",
        condition: "excellent",
        conditionText: "Perfeito estado - 2 anos de uso",
        images: ["images/IMG_4128.jpg", "images/IMG_4129.jpg", "images/IMG_4130.jpg", "images/IMG_4131.jpg"],
        placeholder: "🍽️",
        available: null,
        sold: false
    },
    {
        id: 11,
        title: "Aparador Grande Madeira (2,02m)",
        category: "moveis",
        price: 1250,
        originalPrice: 2500,
        description: "Envelopado branco, 3 portas. Dimensoes: 2,02m x ~50cm x ~90-100cm.",
        condition: "good",
        conditionText: "Bom estado - 7 anos de uso",
        images: [],
        placeholder: "🗄️",
        available: null,
        sold: false
    },
    {
        id: 12,
        title: "Conjunto Mesa Alta + 4 Banquetas Pretas",
        category: "moveis",
        price: 1300,
        originalPrice: 2360,
        description: "Metal preto, tampo de vidro, fibra sintetica/rattan. Largura mesa: 1,96m. Sempre uso interno.",
        condition: "good",
        conditionText: "Bom estado - 4 anos, uso interno",
        images: [],
        placeholder: "🪑",
        available: null,
        sold: false
    },
    {
        id: 13,
        title: "Arvore de Natal 2,20m",
        category: "decoracao",
        price: 500,
        originalPrice: 1200,
        description: "Artificial, verde tradicional. Sem decoracao. Altura: 2,20m.",
        condition: "good",
        conditionText: "Bom estado - 4 anos de uso",
        images: [],
        placeholder: "🎄",
        available: null,
        sold: false
    },
    {
        id: 14,
        title: "Cama Queen + Box Ortobom",
        category: "camas",
        price: 1000,
        originalPrice: 1500,
        description: "OrtoClass Black Pocket System + Box Light Selado Black. Dimensoes: 1,58m x 1,98m x 31cm (box).",
        condition: "fair",
        conditionText: "Bom estado - 10 anos de uso",
        images: [],
        placeholder: "🛏️",
        available: "09/04",
        sold: false
    },
    {
        id: 15,
        title: "Aparador MDF (2m) com Nichos e Gavetas",
        category: "moveis",
        price: 800,
        originalPrice: 1430,
        description: "Nichos + 2 gavetas pretas. Dimensoes: 2m x 75cm x 49cm. Obs: falta 1 puxador + leve defeito embaixo.",
        condition: "fair",
        conditionText: "Estado regular - 7 anos, pequeno defeito",
        images: [],
        placeholder: "🗄️",
        available: null,
        sold: false
    }
];
